<?php
$lang['pt'] = array(
    "LANG_REMOVE" => "Remover",  
    "LANG_ADD" => "Adicionar",  
    "LANG_EDIT" => "Editar",  
    "LANG_SETTINGS" => "Definições",
    "LANG_DASHBOARD" => "Painel",
    "LANG_PAGES" => "Páginas",
    "LANG_NEW_PAGE" => "Adicionar página",
    "LANG_ALL_PAGES" => "Listar páginas",
    "LANG_NO_PAGES" => "Não existem páginas",
    "LANG_USERS" => "Utilizadores",
    "LANG_NEW_USER" => "Adicionar utilizador",
    "LANG_ALL_USERS" => "Listar utilizadores",
    "LANG_IMAGES" => "Imagens",
    "LANG_UPLOAD_IMAGE" => "Carregar imagem",
    "LANG_DOCUMENTS" => "Documentos",
    "LANG_AGO" => "atrás",
    "LANG_NAME" => "Nome",
    "LANG_CREATED" => "Criado",
    "LANG_CREATED_BY" => "Criado por",
    "LANG_ACTIONS" => "Acções",
    "LANG_LAST_LOGIN" => "Último Login a",
    "LANG_LAYOUTS" => "Layouts",
    "LANG_NO_LAYOUTS" => "Não existem layouts"
);
